version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_ddl:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - elixir-grpc-example-network
  backend:
    image: poad/java-grpc-elixir-service-example
    container_name: java-grpc-elixir-service-example
    environment:
      GRPC_ENDPOINT: 172.17.0.1
    depends_on:
      - mysql
    ports:
      - 50051:50051
    links:
      - mysql
    networks:
      - elixir-grpc-example-network
  frontend:
    build:
      context: ./elixir_api_server
      dockerfile: Dockerfile
    container_name: elixir_api_server
    environment:
      GRPC_ENDPOINT: 172.17.0.1
    ports:
      - 8000:8000
    networks:
      - elixir-grpc-example-network
networks:
  elixir-grpc-example-network:
  default:
    external:
      name: elixir-grpc-example-network
