// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.poad.example.grpc;

public interface DeleteMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.DeleteMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.message.UUIDEntity id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.message.UUIDEntity id = 1;</code>
   */
  com.github.poad.example.grpc.UUIDEntity getId();
  /**
   * <code>.message.UUIDEntity id = 1;</code>
   */
  com.github.poad.example.grpc.UUIDEntityOrBuilder getIdOrBuilder();
}
