# spring.profiles.activeにデフォルトでアクティブなプロファイルを指定
spring:
  profiles:
    active: dev
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      transaction-type: RESOURCE_LOCAL
  data:
    jpa:
      repositories:
        enabled: true

grpc:
  enableReflection: true
  port: 50051

# "---"でプロファイルを区切る
# プロファイル名はspring.profilesに書く
---
spring:
  profiles: dev
  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: ""
    type: org.apache.tomcat.jdbc.pool.DataSource
#    tomcat:
#      jdbc-interceptors: com.amazonaws.xray.sql.mysql.TracingInterceptor
---
spring:
  profiles: docker-compose
  datasource:
    tomcat:
      max-active: 100
      initial-size: 10
      test-on-borrow: true
      validation-query: SELECT 1
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/test
    username: root
    password: ""
    type: org.apache.tomcat.jdbc.pool.DataSource
#    tomcat:
#      jdbc-interceptors: com.amazonaws.xray.sql.mysql.TracingInterceptor

