// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.poad.example.grpc;

public interface GetMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.GetMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.message.UUIDEntity id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.message.UUIDEntity id = 1;</code>
   * @return The id.
   */
  com.github.poad.example.grpc.UUIDEntity getId();
  /**
   * <code>.message.UUIDEntity id = 1;</code>
   */
  com.github.poad.example.grpc.UUIDEntityOrBuilder getIdOrBuilder();
}
