// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.poad.example.grpc;

public interface MessageEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.MessageEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.message.UUIDEntity id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.message.UUIDEntity id = 1;</code>
   * @return The id.
   */
  com.github.poad.example.grpc.UUIDEntity getId();
  /**
   * <code>.message.UUIDEntity id = 1;</code>
   */
  com.github.poad.example.grpc.UUIDEntityOrBuilder getIdOrBuilder();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
