// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.poad.example.grpc;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_UUIDEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_UUIDEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_GenerateUUIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_GenerateUUIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MessageEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_MessageEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_GetMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_GetMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_GetMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_GetMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_DeleteMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_DeleteMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_DeleteMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_DeleteMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_CountMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_CountMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MessageCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_MessageCount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_DeleteMessagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_DeleteMessagesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MessagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_MessagesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007message\"\033\n\nUUIDEntity\022\r" +
      "\n\005value\030\001 \001(\t\"\025\n\023GenerateUUIDRequest\"A\n\r" +
      "MessageEntity\022\037\n\002id\030\001 \001(\0132\023.message.UUID" +
      "Entity\022\017\n\007message\030\002 \001(\t\"4\n\021GetMessageReq" +
      "uest\022\037\n\002id\030\001 \001(\0132\023.message.UUIDEntity\"\024\n" +
      "\022GetMessagesRequest\"\027\n\025DeleteMessagesReq" +
      "uest\"7\n\024DeleteMessageRequest\022\037\n\002id\030\001 \001(\013" +
      "2\023.message.UUIDEntity\"\026\n\024CountMessagesRe" +
      "quest\"\035\n\014MessageCount\022\r\n\005count\030\001 \001(\003\"\030\n\026" +
      "DeleteMessagesResponse\"<\n\020MessagesRespon" +
      "se\022(\n\010messages\030\001 \003(\0132\026.message.MessageEn" +
      "tity2T\n\rUUIDGenerator\022C\n\014GenerateUUID\022\034." +
      "message.GenerateUUIDRequest\032\023.message.UU" +
      "IDEntity\"\0002\301\003\n\tMessenger\022B\n\nGetMessage\022\032" +
      ".message.GetMessageRequest\032\026.message.Mes" +
      "sageEntity\"\000\022H\n\014ListMessages\022\033.message.G" +
      "etMessagesRequest\032\031.message.MessagesResp" +
      "onse\"\000\022>\n\nPutMessage\022\026.message.MessageEn" +
      "tity\032\026.message.MessageEntity\"\000\022H\n\rDelete" +
      "Message\022\035.message.DeleteMessageRequest\032\026" +
      ".message.MessageEntity\"\000\022S\n\016DeleteMessag" +
      "es\022\036.message.DeleteMessagesRequest\032\037.mes" +
      "sage.DeleteMessagesResponse\"\000\022G\n\rCountMe" +
      "ssages\022\035.message.CountMessagesRequest\032\025." +
      "message.MessageCount\"\000B4\n\034com.github.poa" +
      "d.example.grpcB\014MessageProtoP\001\242\002\003MSGb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_message_UUIDEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_UUIDEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_UUIDEntity_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_message_GenerateUUIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_GenerateUUIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_GenerateUUIDRequest_descriptor,
        new java.lang.String[] { });
    internal_static_message_MessageEntity_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_MessageEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_MessageEntity_descriptor,
        new java.lang.String[] { "Id", "Message", });
    internal_static_message_GetMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_message_GetMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_GetMessageRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_message_GetMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_message_GetMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_GetMessagesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_message_DeleteMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_message_DeleteMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_DeleteMessagesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_message_DeleteMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_message_DeleteMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_DeleteMessageRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_message_CountMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_message_CountMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_CountMessagesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_message_MessageCount_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_message_MessageCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_MessageCount_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_message_DeleteMessagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_message_DeleteMessagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_DeleteMessagesResponse_descriptor,
        new java.lang.String[] { });
    internal_static_message_MessagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_message_MessagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_MessagesResponse_descriptor,
        new java.lang.String[] { "Messages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
