// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.poad.example.grpc;

public interface MessageCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.MessageCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 count = 1;</code>
   */
  long getCount();
}
