// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.poad.example.grpc;

public interface MessagesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.MessagesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .message.MessageEntity messages = 1;</code>
   */
  java.util.List<com.github.poad.example.grpc.MessageEntity> 
      getMessagesList();
  /**
   * <code>repeated .message.MessageEntity messages = 1;</code>
   */
  com.github.poad.example.grpc.MessageEntity getMessages(int index);
  /**
   * <code>repeated .message.MessageEntity messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .message.MessageEntity messages = 1;</code>
   */
  java.util.List<? extends com.github.poad.example.grpc.MessageEntityOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .message.MessageEntity messages = 1;</code>
   */
  com.github.poad.example.grpc.MessageEntityOrBuilder getMessagesOrBuilder(
      int index);
}
