// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.poad.example.grpc;

public interface UUIDEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.UUIDEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
