// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.poad.example.grpc;

public interface GenerateUUIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.GenerateUUIDRequest)
    com.google.protobuf.MessageOrBuilder {
}
