version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_ddl:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - java-to-java-grpc-example-network
  backend:
    image: poad/java-grpc-service-example
    container_name: java-grpc-service-example
    environment:
      GRPC_ENDPOINT: 172.17.0.1
    depends_on:
      - mysql
    ports:
      - 50051:50051
    links:
      - mysql
    networks:
      - java-to-java-grpc-example-network
  frontend:
    image: poad/java-grpc-api-example
    container_name: java-grpc-api-example
    environment:
      GRPC_ENDPOINT: 172.17.0.1
    depends_on:
      - backend
    ports:
      - 8080:8080
    networks:
      - java-to-java-grpc-example-network
networks:
  java-to-java-grpc-example-network:
  default:
    external:
      name: java-to-java-grpc-example-network
